RELAY_PIN = 33
RELAY_ON_VALUE = 1
RELAY_OFF_VALUE = 0

WIFI_SSID = "Password nahi dunga"
WIFI_PASSWORD = "qqqqqqqq"

HTTP_PORT = 8080

DEFAULT_RUN_SECONDS = 3
MAX_RUN_SECONDS = 15

# Audio Settings
MIC_SCK_PIN = 12 
MIC_WS_PIN = 0
MIC_SD_PIN = 2
RECORD_SECONDS = 5